=== raducornea/Review-Programe/continut/programe.dtd
<!ELEMENT programe (program+)>

<!ELEMENT program ((titlu+), (video_link+), (image+), (text+))>
<!ATTLIST program id CDATA #REQUIRED>

<!ELEMENT titlu (#PCDATA)>
<!ELEMENT video_link (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT text (#PCDATA)>

=== raducornea/Review-Programe/resurse/programe.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE programe SYSTEM "programe.dtd">

<programe>
    <program id="1">  <!-- id="1" == nume=valoare-->
        <titlu>Skype Desktop</titlu>
        <video_link>un link</video_link>
        <image>o imagine</image>
        <text>text despre program</text>
    </program>

    <program id="2">
        <titlu>Discord App</titlu>
        <video_link>alt link cool</video_link>
        <image>o imagine frumoasa</image>
        <text>another tutorial cool text</text>
    </program>
    
    <program id="3">
        <titlu>Steam</titlu>
        <video_link>inca un link la site</video_link>
        <image>o imagine cu steam yay</image>
        <text>another tutorial cool text</text>
        <text>review and stuff la program</text>
    </program>

</programe>

=== raducornea/Review-Programe/programe.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE programe SYSTEM "programe.dtd">

<programe>
    <program id="1">  <!-- id="1" == nume=valoare-->
        <titlu>Skype Desktop</titlu>
        <video_link>un link</video_link>
        <image>o imagine</image>
        <text>text pentru tutorial</text>
    </program>

    <program id="2">
        <titlu>Discord App</titlu>
        <video_link>alt link cool</video_link>
        <image>o imagine frumoasa</image>
        <text>another tutorial cool text</text>
    </program>
</programe>
